services:
  app:
    tty: true
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    volumes:
      - ..:/app:cached
      - app-node:/app/node_modules

volumes:
  app-node:
